# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://geel.maartenvanhoof.be
encoding:         UTF-8

# Custom vars
current_version:  0.1.0
repo:             https://github.com/vanhoofmaarten/geel

download_source:  https://github.com/vanhoofmaarten/geel/archive/master.zip
